/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookBookIdReadRouteImport } from './routes/book.$bookId.read'
import { Route as BookBookIdEditRouteImport } from './routes/book.$bookId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdReadRoute = BookBookIdReadRouteImport.update({
  id: '/book/$bookId/read',
  path: '/book/$bookId/read',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdEditRoute = BookBookIdEditRouteImport.update({
  id: '/book/$bookId/edit',
  path: '/book/$bookId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/book/$bookId/edit': typeof BookBookIdEditRoute
  '/book/$bookId/read': typeof BookBookIdReadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/book/$bookId/edit': typeof BookBookIdEditRoute
  '/book/$bookId/read': typeof BookBookIdReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/book/$bookId/edit': typeof BookBookIdEditRoute
  '/book/$bookId/read': typeof BookBookIdReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/book/$bookId/edit'
    | '/book/$bookId/read'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/login' | '/book/$bookId/edit' | '/book/$bookId/read'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/book/$bookId/edit'
    | '/book/$bookId/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  BookBookIdEditRoute: typeof BookBookIdEditRoute
  BookBookIdReadRoute: typeof BookBookIdReadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/read': {
      id: '/book/$bookId/read'
      path: '/book/$bookId/read'
      fullPath: '/book/$bookId/read'
      preLoaderRoute: typeof BookBookIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/edit': {
      id: '/book/$bookId/edit'
      path: '/book/$bookId/edit'
      fullPath: '/book/$bookId/edit'
      preLoaderRoute: typeof BookBookIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  BookBookIdEditRoute: BookBookIdEditRoute,
  BookBookIdReadRoute: BookBookIdReadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
